# Generated by Django 4.1.7 on 2023-03-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_remove_shops_address_id_shops_house_shops_street_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shops',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='shops',
            name='open_time',
        ),
        migrations.AddConstraint(
            model_name='shops',
            constraint=models.UniqueConstraint(fields=('name', 'street_id', 'house'), name='uniqueShopByAddress'),
        ),
        migrations.AddConstraint(
            model_name='street',
            constraint=models.UniqueConstraint(fields=('name', 'city_id'), name='uniqueStreetByCity'),
        ),
    ]
