# Generated by Django 4.1.7 on 2023-03-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_remove_shops_close_time_remove_shops_open_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='close_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='open_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
